### PR TITLE
Change port to instance to remove some confusion

### PR DESCRIPTION
**Pull request by arj03**
I was trying to get this working but was very confused from the README. It wasn't until I started reading the examples dir that I really understood how to configure this.

One of the confusing things was that there was a port concept, which really was an instance concept and the words was used interchangeably. This PR change all references of port to instance.

Furthermore I cleaned up the README as to, at least for me, make it easier configure and get running.

### CODE REVIEW

**Comment by staltz** [comment]
LGTM

**Comment by arj03** [comment]
Thanks for the review @staltz

**Comment by arj03** [comment]
I guess this should be released as a version 2.0.0, as its not backwards compatible?

**Comment by staltz** [comment]
@arj03 Hmm, interesting, I'm not sure that it's a breaking change, but it's safer to assume that it is, and I don't think it hurts to publish 2.0.0, so we could do that. What about the version in the plugin object? i.e.

```js
exports.name = 'tunnel'
exports.version = '1.0.0' // <------------
exports.manifest = {
  announce: 'sync',
  connect: 'duplex',
  ping: 'sync'
}
```

**Comment by arj03** [comment]
Ohh that's wrong, it should require package.json. I'll fix that a bit later and do a release. Thanks :-)

**Pull request merged**
